class FieldMapper:
    @staticmethod
    def get_field_mapping_api1():
        return {
            "sys_class_name": "Tipo de tarefa",
            "number": "Número",
            "category": "Categoria",
            "subcategory": "Subcategoria",
            "business_service": "Serviço",
            "service_offering": "Oferta de serviço",
            "assignment_group": "Grupo de Atribuição",
            "impact": "Impacto",
            "urgency": "Urgência",
            "priority": "Prioridade",
            "state": "Estado",
            "u_priority_inc": "Priorizar Incidente",
            "problem_id": "Problema",
            "opened_at": "Aberto",
            "resolved_at": "Resolvido",
            "closed_at": "Encerrado",
            "contact_type": "Canal",
            "location": "Local",
            "short_description": "Descrição resumida",
            "u_problem_description": "Descrição",
            "caller_id": "Aberto por",
            "opened_by": "Solicitante",
            "sys_id": "ID do usuário",
            "Senior Manager": "Senior Manager",
            "Gerente": "Gerente",
            "assigned_to": "Atribuído a",
            "close_code": "Código de resolução",
            "u_sub_close_code": "Sub-Código de Resolução",
            "actions_taken": "Anotações de resolução",
            "reopen_count": "Contagem de reaberturas",
            "number": "Número",
            "sys_updated_on": "Atualizado em",
            "sys_updated_by": "Atualizado por",
        }

    @staticmethod
    def get_field_mapping_api2():
        return {
            "sys_class_name": "Tipo de tarefa",
            "number": "Número",
            "request": "Solicitação",
            "cat_item": "Item",
            "business_service": "Serviço",
            "service_offering": "Oferta de serviço",
            "assignment_group": "Grupo de Atribuição",
            "impact": "Impacto",
            "urgency": "Urgência",
            "priority": "Prioridade",
            "state": "Estado",
            "u_prioritize_req": "Priorizar solicitação",
            "opened_at": "Aberto",
            "u_resolved_at": "Resolved at",
            "closed_at": "Encerrado",
            "location": "Local",
            "short_description": "Descrição resumida",
            "u_problem_description": "Descrição",
            "caller_id": "Aberto por",
            "requested_for": "Solicitado(a) para",
            "sys_id": "ID do usuário",
            "Senior Manager": "Senior Manager",
            "Gerente": "Gerente",
            "assigned_to": "Atribuído a",
            "u_reopen_count": "Reaberto",
            "sys_updated_on": "Atualizado em:",
            "sys_updated_by": "Atualizado por",
            "Em qual site você deseja receber o serviço?": "Em qual site você deseja receber o serviço?",
            "Justifique sua necessidade": "Justifique sua necessidade",
            "Descreva detalhadamente o que deseja": "Descreva detalhadamente o que deseja",
        }
